In [36]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn

In [37]:
print(sklearn.__version__)

1.9.1

**Q1.** Pandas version

What's the version of Pandas that you installed?

In [38]:
pd.__version__

'3.0.0'

In [39]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"
df = pd.read_csv(url)

In [40]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 1.1 MB

In [42]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [43]:
len(df)

10000

**Q2.** Records count

How many records are in the dataset?

**10000**

**Q3.** Fuel types 

How many fuel types are presented in the dataset?

3

In [44]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

**Q4. Missing values**

How many columns in the dataset have missing values?

**2**

In [45]:
(df.isnull().sum() > 0).sum()

np.int64(2)

**Q5.** Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

**23.75**

In [46]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

I can also find the answer with Groupby

In [47]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

**Q6. Median value of horsepower**

1) Find the median value of horsepower column in the dataset. **254.0**
2) Next, calculate the most frequent value of the same horsepower column. **252**
3) Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
4) Now, calculate the median value of horsepower once again. **152** . Has it changed? Yes, it decreased

In [48]:
df.horsepower.median()

np.float64(254.0)

In [49]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [50]:
df['horsepower'] = df['horsepower'].fillna(152)

In [51]:
df['horsepower'].isnull().sum()

np.int64(0)

In [52]:
df.horsepower.median()

np.float64(252.0)

**Q7. Sum of weights**

1) Select all the cars from Asia
2) Select only columns vehicle_weight and model_year
3) Select the first 7 values
4) Get the underlying NumPy array. Let's call it X.
5) Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6) Invert XTX.
7) Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8) Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9) What's the sum of all the elements of the result?

In [53]:
df_asia = df[df['origin']=='Asia']
df_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,152.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [55]:
df_asia_reduced = df_asia[['vehicle_weight','model_year']]

In [57]:
df_asia_reduced.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [58]:
X = np.array(df_asia_reduced.head(7))
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [61]:
# Create the transpose of X
XT = X.T #we can use X.transpose() too

In [63]:
# Create the transpose of X
XTX = XT.dot(X)

In [64]:
#Invert XTX
XTX_inv = np.linalg.inv(XTX)

In [65]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [66]:
XTX_invXT =XTX_inv.dot(XT)
w = XTX_invXT.dot(y)

In [67]:
w.sum()

np.float64(0.36919696904927535)

What is the sum of the result **Answer**: 0.3691

***The details below are for my own understanding of how vector and matrix operations work***

**Vector - vector multiplication**

Le resultat du vector vector multiplication est le résultat d'une addition, soit un chiffre

In [ ]:
U = np.array([2, 4, 5, 6]).transpose()

In [ ]:
V = np.array([1,0,0,2])

In [ ]:
U.dot(V)

**Matrix - vector multiplication**

Renvoi un vector aussi large que le nombre de rangée de la matrice. Donc si la matrice a 3 rangées, le vector fruit de la multiplication matrice vector aura 3 chiffres, 3 rangées

In [ ]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [ ]:
v = np.array([1, 0.5, 2, 1])

In [ ]:
Uv = U.dot(V)

In [ ]:
Uv.shape

**Matrix - Matrix multiplication**

In [ ]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1,0],
])

In [ ]:
V

In [ ]:
U.dot(V)